// Sales Analytics Constants
export const SALES_ANALYTICS_REQUEST = 'SALES_ANALYTICS_REQUEST';
export const SALES_ANALYTICS_SUCCESS = 'SALES_ANALYTICS_SUCCESS';
export const SALES_ANALYTICS_FAIL = 'SALES_ANALYTICS_FAIL';
export const SALES_ANALYTICS_RESET = 'SALES_ANALYTICS_RESET';

// Product Analytics Constants
export const PRODUCT_ANALYTICS_REQUEST = 'PRODUCT_ANALYTICS_REQUEST';
export const PRODUCT_ANALYTICS_SUCCESS = 'PRODUCT_ANALYTICS_SUCCESS';
export const PRODUCT_ANALYTICS_FAIL = 'PRODUCT_ANALYTICS_FAIL';
export const PRODUCT_ANALYTICS_RESET = 'PRODUCT_ANALYTICS_RESET';

// Customer Analytics Constants
export const CUSTOMER_ANALYTICS_REQUEST = 'CUSTOMER_ANALYTICS_REQUEST';
export const CUSTOMER_ANALYTICS_SUCCESS = 'CUSTOMER_ANALYTICS_SUCCESS';
export const CUSTOMER_ANALYTICS_FAIL = 'CUSTOMER_ANALYTICS_FAIL';
export const CUSTOMER_ANALYTICS_RESET = 'CUSTOMER_ANALYTICS_RESET';

// Order Analytics Constants
export const ORDER_ANALYTICS_REQUEST = 'ORDER_ANALYTICS_REQUEST';
export const ORDER_ANALYTICS_SUCCESS = 'ORDER_ANALYTICS_SUCCESS';
export const ORDER_ANALYTICS_FAIL = 'ORDER_ANALYTICS_FAIL';
export const ORDER_ANALYTICS_RESET = 'ORDER_ANALYTICS_RESET';

// Financial Summary Constants
export const FINANCIAL_SUMMARY_REQUEST = 'FINANCIAL_SUMMARY_REQUEST';
export const FINANCIAL_SUMMARY_SUCCESS = 'FINANCIAL_SUMMARY_SUCCESS';
export const FINANCIAL_SUMMARY_FAIL = 'FINANCIAL_SUMMARY_FAIL';
export const FINANCIAL_SUMMARY_RESET = 'FINANCIAL_SUMMARY_RESET';
